---
name: nginx

releases:
- name: nginx
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 456.25

instance_groups:
- name: nginx-1.17.3
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: nginx
    release: nginx
  vm_type: default
  networks:
  - name: default
  stemcell: default
